# Change these first
owner: luke-beep # Your GitHub organization or username, where this repository lives
repo: status.lukehjo.tech # The name of this repository

sites:
  - name: LukeHjo's Dev Log
    url: https://dev.lukehjo.tech
  - name: lukehjo.tech
    url: https://lukehjo.tech
  - name: lukehjo.tech Mail
    url: https://webmail.lukehjo.tech
  - name: LukeHjo's Dev Forum
    url: https://forum.lukehjo.tech

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lukehjo.tech
  logoUrl: https://raw.githubusercontent.com/luke-beep/status.lukehjo.tech/master/assets/asset.svg
  name: LukeHjo's Dev Log Status
  introTitle: "LukeHjo's Dev Log Status"
  introMessage: "Welcome to LukeHjo's Dev Status Page!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/luke-beep/status.lukehjo.tech
    - title: Website
      href: https://dev.lukehjo.tech/
    - title: Forum
      href: https://forum.lukehjo.tech

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
